sudo: required
language: node_js
node_js:
  - "8"
branches:
  only:
  - master
  - dev
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
before_install:
- export DISPLAY=:99.0
- cd packages/mip
install:
- travis_retry npm install
script:
- npm run test:cover
after_success:
- cat ./coverage/lcov.info | coveralls